spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: "sa"
    password: ""